New RANS models
Nek5000/nekRS pull request #600
Opened 2024-10-23 15:27 UTC by nandu90

The following RANS models are now available:
- KTAU (standard) --> default model
- SST (ktau SST model)
- SST+DDES (ktau SST Delayed Detached Eddy Simulation)
- SST+IDDES (ktau SST Improved Delayed Detached Eddy Simulation)

SST based models require ywd array. User has the option to pass it through RANS::setup. If not provided, the default is to use cheap_dist

The turbulent Prandtl number in `ktauChannel` case is changed to 0.85 (from 0.7)

Pending: CI setup of `periodicHill` case for DDES model(s)

2024-10-23 17:58 UTC, stgeke requested changes

2024-10-23 17:58 UTC, stgeke commented on examples/periodicHill/ci.inc
> +  const auto lenLES = 4.69;
Please use CiEvalTest(). You'll find an example in ethier.

2024-10-23 17:58 UTC, stgeke commented on examples/periodicHill/periodicHill.oudf
> +@kernel void scalarScaledAdd(const dlong N,
A kernel like this should be not needed. Use a `linAlg` function instead.

2024-10-23 17:58 UTC, stgeke commented on examples/periodicHill/ci.oudf
> +@kernel void tauWallKernel(const dlong Nelements,
Why is this kernel needed? Can't we use the existing drag functio?

2024-10-23 17:58 UTC, stgeke commented on examples/periodicHill/periodicHill.par
> +polynomialOrder = 3
I don't think we should add an example with such a low polynomial order. It's considered to be bad practice to use a polynomial order < 5.

2024-10-23 17:58 UTC, stgeke commented on examples/periodicHill/periodicHill.udf
> +	/* if(ciMode) { */
remove commented code sections like this

2024-10-23 17:58 UTC, stgeke commented on examples/periodicHill/periodicHill.udf
> +  //if(nrs->isCheckpointStep) nek::userchk();
remove commented code sections like this

2024-10-23 17:58 UTC, stgeke commented on examples/periodicHill/periodicHill.udf
> +  //if(nrs->isCheckpointStep) tavg::outfld();
remove commented code sections like this

2024-10-23 17:58 UTC, stgeke commented on examples/periodicHill/periodicHill.usr
> +      subroutine useric(ix,iy,iz,ieg) ! set up initial conditions
use `UDF_Setup` instead of `useric`

2024-10-23 17:58 UTC, stgeke commented on src/nrs/plugins/kernels/RANSktau.okl
> +  const dfloat stmagn = sqrt(2.0 * stmag2);//note: stmag2 is missing factor 2
comment is confusing

2024-10-23 18:01 UTC, stgeke commented
PR doesn't compile with latest `next`.

2024-10-25 02:37 UTC, nandu90 commented on examples/periodicHill/ci.inc
> +  const auto lenLES = 4.69;
Changed to CiEvalTest()

2024-10-25 02:39 UTC, nandu90 commented on examples/periodicHill/ci.oudf
> +@kernel void tauWallKernel(const dlong Nelements,
I need to extract tauwall pointwise GLL array along the wall to test it against LES data. The drag function returns integrated value.

2024-10-25 02:43 UTC, nandu90 commented on examples/periodicHill/periodicHill.par
> +polynomialOrder = 3
I have changed polynomial order to 5. It was a challenge to keep CI test under 3 minutes. I have reduced the mesh size significantly to keep computational cost minimum.

2024-10-25 02:43 UTC, nandu90 commented on examples/periodicHill/ci.oudf
> +@kernel void tauWallKernel(const dlong Nelements,
The CI test for this case calculates the error norm of computed tau wall values against LES data (from NASA's website)

2025-09-18 12:50 UTC, closed without merging